### ISSUE TITLE
Unable to rerun workflow

### ISSUE THREAD

**Issue by AdamBanham** [mnaeimaei/MIMICIII-Event-Graph#1]
Hi, 

I have recently read the preprint for "Discovering care pathways for multi-morbid patients using event graphs". I had hoped to rerun your work to inspect some of the interesting dfgs that were shown in the paper. 

However, the repo does not include the pre-processing scripts to the create the mentioned event logs in the paper.  Can you make these available?

In Step 2, you reference a local file called config.csv on line 7, can you share this csv? 

I have also noted that a step may be missing as step 3 is connecting to some local instance. Could you explain what this local instance is? 

Also in step 3, is the variable 'path_to_neo4j_import_directory' meant to pointed at the same directory which was used in step 1? 

Also what version of python was used for your scripts? e.g. python 3.7.x or python 3.8.x or python 3.9.x 

Finally, is the p.py file meant to be implemented?

Very cool work, looking forward to see your graphs

**Comment by mnaeimaei** [comment]
Hi Adam



   - For pre-processing, I used SQL scripts on MIMIC-III Database. Since
   several CSV files of that database were used, many different queries were
   conducted.



   - Yes, for step 2, a CSV file was used as an input to produce more
   accessible following *Lists (and List of Lists)* as you see it in step3
   python files.


include_entities =  ['Logistic', 'Laboratory_Measurement', 'Prescriptions',
'Diagnosis',
                     'Case_LM', 'Case_LP', 'Case_LD', 'Case_MP', 'Case_MD',
'Case_PD', 'Adm']
case_entity =  ['Case_All']

model_entities =  [['Logistic', 'case', 'WHERE e.EventOrigin ="Logistic"'],
                   ['Laboratory_Measurement', 'case', 'WHERE e.EventOrigin
="Laboratory_Measurement"'],
                   ['Prescriptions', 'case', 'WHERE e.EventOrigin
="Prescriptions"'],
                   ['Diagnosis', 'case', 'WHERE e.EventOrigin
="Diagnosis"'],
                   ['Case_All', 'case', 'WHERE EXISTS(e.case)'],
                   ['Adm', 'HADM_ID', 'WHERE EXISTS(e.HADM_ID)']]

model_relations =  [['Case_LM', 'Logistic', 'Laboratory_Measurement',
'case'],
                    ['Case_LP', 'Logistic', 'Prescriptions', 'case'],
                    ['Case_LD', 'Logistic', 'Diagnosis', 'case'],
                    ['Case_MP', 'Laboratory_Measurement', 'Prescriptions',
'case'],
                    ['Case_MD', 'Laboratory_Measurement', 'Diagnosis',
'case'],
                    ['Case_PD', 'Prescriptions', 'Diagnosis', 'case']]

model_entities_derived =  ['Case_LM', 'Case_LP', 'Case_LD', 'Case_MP',
'Case_MD', 'Case_PD']

attr_relations =  [['Adm', 'HADM_ID', 'Admission']]


But the problem is I faced an issue two weeks ago with my laptop hard, and
I lost many of my files, such as that CSV. I will upload the new CSV file
before the PODS4H conference, or maybe I will update step2 to be done
without the need for any CSV file.



   - I didn't understand this question (I have also noted that a step may
   be missing as step 3 is connecting to some local instance. Could you
   explain what this local instance is?); could you please explain more ?



   - The 'path_to_neo4j_import_directory' is a location in which you put
   the output of step1. When you create a project in Neo4J, you should import
   the step1 output there.



   - The version of python was 3.8.x



   - The p.py file no need to be executed; I removed it


I will update the ReadMe for the repo in the following days.


Good luck and Good day
Milad

**Comment by AdamBanham** [comment]
Thanks for the reply Milad,

Sorry to hear about your laptop. That sucks, I have been there myself.

>  I didn't understand this question (I have also noted that a step may be missing as step 3 is connecting to some local instance. Could you explain what this local instance is?); could you please explain more?

In 'MIMIC3_Step3_import.py' at line 6:
`driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "1234"))`

I have intercepted this line as that you have some local instance of a database server running and this script connects to. I do not have any experience with neo4j so I am not sure what this means. I also didn't see any mention of the setup of neo4j project within your readme. If you are going to expand the readme, could you include some direction for people that are not familiar with neo4j?

>  For pre-processing, I used SQL scripts on MIMIC-III Database. Since several CSV files of that database were used, many different queries were conducted.
   
If you still have the SQL scripts you used, I would be interested to see what pre-processing you did on the data. As I have used the MIMIC-III data for a paper as well, but during my work, I found no need to do any preprocessing on the data itself. I ran  ETL
scripts to get data then processed the extracted data into an event log format for my needs. 

I will check back when you have had the time to update the workflow before attempting to rerun.

Thanks for your time.

**Comment by mnaeimaei** [comment]
Hi

*Before running step 3: *

1. In Neo4j Desktop 1.4.4, you should create a new project in Neo4J; then,
you will Add Local DBMS to your project and select a password (here 1234
because of line 6).

Then in your project setting, you should allocate enough memory to your
database, advised: *dbms.memory.heap.max_size=20G*

Finally, you import the output of the step1 in your Neo4j project (open
folder/import)


2. In MIMIC3_Step3_import.py

the *include_entities , case_entity , model_entities , model_relations ,
model_entities_derived , attr_relations *should be adopt with your imported
event log


*About driver = GraphDatabase.driver("bolt://localhost:7687",
auth=("neo4j", "1234"))*

This line holds the details required to establish a connection with a Neo4j
database.

The driver() class holds the details required to establish connections with
a Neo4j database, including server URIs, credentials, and other
configurations.

*driver(“the connection URI for the driver”, auth=(”user”,
“password”),max_connection_lifetime = Number which is maximum duration in
seconds that the driver will keep a connection for before being removed
from the pool)*

Example


*from packageName import Subpackage*

*variable = Subpackage.className(argument) //variable as a class insta*nce

in In MIMIC3_Step3_import.py

*from neo4j import GraphDatabase*

*driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j",
"1234"))*


Sure, I will expand the readme-files as soon as possible.


I just used reverse engineering for pre-processing; for example, I need an
event log likes Table 4 of the paper as an input of step1. So I achieved
that by SQL from the different MIMIC tables; I used GoogleBQ for database
management.


Thank you

Milad

**Comment by mnaeimaei** [comment]
Hi

The repo was updated:

1. A CSV file derived from MIMIC-III was pushed.
2. Step2.py was removed
3. Step3.py was renamed to Step2.py.
4. Step4.py was updated and renamed to Step3.py

Milad

**Comment by AdamBanham** [comment]
Hi Milad,

Thanks for the quick update, your readme is great but it has a few typo's. Some of the wording in the steps is a bit confusing as well. For example:

> Create a new project in Neo4J, Addi a Local DBMS to that project, and select a password (1234 recommended).
> Then in the project setting, allocate enough memory to the database, such as DBMS.memory.heap.max_size=20G
> import the output of the step1 in that Neo4j project (open folder/import)
> start Neo4J Project

Line 3 could be reworded as "Copy the file created by step one, 'MIMICfull.csv' (which will be located at directory which path_to_neo4j_import_directory is set to), into import directory for the new Neo4J project. This directory can be found by clicking open folder > import,  through the Neo4J UI."

Also when you included the following in the readme:

> Install other libraries pandas, time, os, CSV, graphviz

Are you referring to the built libraries, 'time', 'os' , 'csv'? If so you should not need to install these libraries as they are part of python's core modules.

I also installed the xdot, python library, https://pypi.org/project/xdot/. As your final python scirpt produced a pdf without it but did throw a warning about not having access to the CLI for the library.

However, when I run step two, I get the following error: 

> File ".\MIMIC3_Step2_import.py", line 362, in <module>
>     runQuery(driver, 'DROP CONSTRAINT ON (e:Event) ASSERT e.ID  IS UNIQUE;')
>   File ".\MIMIC3_Step2_import.py", line 127, in runQuery
>     result = session.run(query).single()
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\work\simple.py", line 232, in run
>     self._autoResult._run(
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\work\result.py", line 143, in _run
>     self._attach()
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\work\result.py", line 232, in _attach
>     self._connection.fetch_message()
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\work\result.py", line 63, in inner
>     func(*args, **kwargs)
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\io\_bolt4.py", line 271, in fetch_message
>     response.on_failure(summary_metadata or {})
>   File "C:\Users\n7176546\.virtualenvs\MIMICIII-Event-Graph-vAl1tmyx\lib\site-packages\neo4j\io\_common.py", line 184, in on_failure
>     raise Neo4jError.hydrate(**metadata)
> neo4j.exceptions.DatabaseError: {code: Neo.DatabaseError.Schema.ConstraintDropFailed} {message: Unable to drop constraint on (:Event {ID}): No such constraint (:Event {ID}).}

I was able to run step 2 after changing the following on line 51:
`step_ClearConstraints = False`

However, I was able to rerun the rest of your workflow, to produce the pdf.
![image](https://user-images.githubusercontent.com/38652037/137276425-5f06b121-b736-49a9-a450-c8f8b7d64469.png)

Over the weekend, I will see if I can adapt your code to use one of smaller logs I have extracted from MIMICIII.

Thanks for all your effort!
